// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuFCYEnB8Z9Kg0cVrJTQBoCCeVyhaRpg0',
    appId: '1:432861693901:android:8a46788691868c2bf8a684',
    messagingSenderId: '432861693901',
    projectId: 'lokakarya-app',
    storageBucket: 'lokakarya-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArPmQwRzOo_pyLKnIgLzsgZCayQQmeLGg',
    appId: '1:432861693901:ios:043257cccbc6da5cf8a684',
    messagingSenderId: '432861693901',
    projectId: 'lokakarya-app',
    storageBucket: 'lokakarya-app.firebasestorage.app',
    iosBundleId: 'com.example.lokakarya',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk5EKWgUdG4ge4JFt0CIcM5IzySAZylFo',
    appId: '1:432861693901:web:47525cb5903d52b2f8a684',
    messagingSenderId: '432861693901',
    projectId: 'lokakarya-app',
    authDomain: 'lokakarya-app.firebaseapp.com',
    storageBucket: 'lokakarya-app.firebasestorage.app',
    measurementId: 'G-97P7283HJQ',
  );

}